version: "1"
services:
  fastapi_app:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: todolist-backend
    environment:
      DB_USER: ${DB_USER}
      DB_PASSWORD: ${DB_PASSWORD}
      DB_PORT: ${DB_PORT}
      DB: ${DB}
      SECRET_KEY: ${MY_SECRET_KEY}
    env_file:
      - .env
    ports:
      - 8080:8080
    networks:
      - backend
    depends_on:
      - db

  db:
    image: postgres:15.1
    container_name: todolist-db
    environment:
      POSTGRES_USER: ${DB_USER}
      POSTGRES_PASSWORD: ${DB_PASSWORD}
      POSTGRES_PORT: ${DB_PORT}
      POSTGRES_DB: ${DB}
    env_file:
      - .env
    volumes:
      - postgres-data:/var/lib/postgresql/data
    networks:
      - backend

networks:
  backend:

volumes:
  postgres-data: